title: e/chaos temple 
email: ilyes.arfaoui01@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: ilyesarf01
github_username:  ilyesarf

bible:
  title: "e/chaos bible"
  baseurl: "/bible"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

#permalink: /:title
#exclude: [bible]
