title: e/chaos bible
email: ilyes.arfaoui01@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Documenting my descent into madness
baseurl: "/bible" 
twitter_username: ilyesarf01
github_username:  ilyesarf

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

